# Generated by Django 3.2 on 2021-04-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='default@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
